const texts = {
    EN: {
        Header: {
            text: "Contact Us",
        },
        BottomNav: {
            benefits: "Advantages",
            menu: "Menu",
            product: "Product",
            forStreamers: "For Streamers",
            faq: "FAQ",
            register: "Register",
        },
        Hero: {
            title: "Monetize    your traffic",
            subtitle: "With a direct advertiser of iGaming products",
        },
        Form: {
            title: "Join Us",
            companyNamePlaceholder: "Company Name",
            emailPlaceholder: "Email",
            phonePlaceholder: "Phone Number",
            searchBarPlaceholder: "Search",
            passwordPlaceholder: "Password",
            repeatPasswordPlaceholder: "Repeat Password",
            agreementServices: "I agree",
            rulesAgreement: "services and policies",
        },
        Benefits: {
            title: "Our Benefits",
            benefitFirst: "Weekly payouts",
            benefitSecond: "Personal manager",
            benefitThird: "Custom creatives",
            benefitFourth: "Apps for rent",
            productCardTitleFirst: "New Products",
            productCardDescriptionFirst: "Take advantage of an empty base of gambling and betting offers with a top reg2dep conversion rate of 20-50% for effective monetization",
            productCardTitleSecond: "Transparent Statistics",
            productCardDescriptionSecond: "Track traffic quality in the affiliate program and optimize advertising campaigns to maximize profit",
            productCardTitleThird: "In-house Development",
            productCardDescriptionThird: "Allows us to continuously develop products tailored to the needs of a rapidly changing market and demonstrate stable growth",
        },
        Faq: {
            title: "FAQ",
            faqItems: [
                { question: "What is the LVLX affiliate program?", answer: "LVLX is a convenient marketing tool used by website owners, streamers, arbitrage specialists, and other performance marketing professionals to drive targeted traffic to gambling and betting offers like GETX." },
                { question: "What is traffic arbitrage?", answer: "It is an earning scheme where a person (arbitrage specialist) buys traffic from one source and redirects it to the advertiser's offers, earning a commission - the difference between the cost of acquiring traffic and the income from conversions." },
                { question: "How to become a partner and earn with LVLX?", answer: "1. Register on the LVLX affiliate program website via the link, wait for a message from the manager who will confirm your access to the personal account and help with the launch.\n2. Attract an audience and earn profits based on the chosen cooperation model: RevShare, CPA, or Hybrid.\n3. Your reward depends on the quantity and quality of traffic.\n" },
                { question: "How and when are payments made?", answer: "For the RevShare model, partner earnings are paid every Tuesday.\nFor CPA and Hybrid models, payments are made twice a month for the periods 1-15 and 16-30(31).\nPayments are made in USDT, BTC, VISA, and MasterCard.\nThe minimum payout amount is $50.\n" },
                { question: "What traffic sources do we accept?", answer: "The LVLX affiliate program accepts all types of traffic, namely: SEO (except SEO for branded keywords of our products), PPC, ASO, UAC, Facebook, In-app, social networks, banner ads, streams. We are also ready to discuss any alternative traffic source.\nProhibited: player deception schemes, misleading, fraud, incentivized traffic, so-called cookie stuffing, playing under your referral link.\nEach launch is agreed upon with a personal affiliate manager.\n" },
                { question: "What are CPA and RevShare, and which model is better to choose?", answer: "CPA is payment for a targeted action, in our case, for the first deposit of the player you brought. The CPA rate depends on the source, quality, and volume of traffic and is discussed individually.\nRevShare is a percentage of the income generated by players. Our affiliate program offers 50% of NGR for life.\nThe choice of model depends on the type of traffic, and our managers will recommend the best option for your growth.\n" },
                { question: "What is a Referral?", answer: "The direct advertiser LVLX allows its partners to earn not only on promoting gambling products and attracting users but also on attracting new webmasters to work with the affiliate program.\nEarn 3% of the referral's income.\n" },
                { question: "Media Information", answer: "For any media cooperation questions, contact our PR department: t.me/afflvlx\n" },
            ],
        },
    },
    RU: {
        Header: {
            text: "Связаться",
        },
        BottomNav: {
            benefits: "Преимущества",
            product: "Продукт",
            menu: "Меню",
            forStreamers: "Стримерам",
            faq: "FAQ",
            register: "Зарегистрироваться",
        },
        Hero: {
            title: "Монетизируй свой трафик",
            subtitle: "С прямым рекламодателем iGaming продуктов",
        },
        Form: {
            title: "Присоединяйся",
            companyNamePlaceholder: "Название компании",
            emailPlaceholder: "Емейл",
            searchBarPlaceholder: "Поиск",
            phonePlaceholder: "Номер телефона",
            passwordPlaceholder: "Пароль",
            repeatPasswordPlaceholder: "Ещё раз",
            agreementServices: "Я принимаю",
            rulesAgreement: "правила и условия",
        },
        Benefits: {
            title: "Наши преимущества",
            benefitFirst: "Выплаты каждую неделю",
            benefitSecond: "Личный менеджер",
            benefitThird: "Кастомные креативы",
            benefitFourth: "Приложения в аренду",
            productCardTitleFirst: "Новые продукты",
            productCardDescriptionFirst: "Воспользуйся преимуществом пустой базы гемблинг и беттинг офферов при " +
                "топовом" +
                " конверте reg2dep 20-50% для эффективной монетизации",
            productCardTitleSecond: "Прозрачная статистика",
            productCardDescriptionSecond: "Отслеживай качество трафика в партнерской программе и оптимизируй " +
                "рекламные " +
                "кампании, чтобы получить максимальный профит",
            productCardTitleThird: "Собственная разработка",
            productCardDescriptionThird: "Позволяет нам нон-стоп развивать продукты под потребности быстро" +
                " меняющегося рынка и показывать стабильный рост",
        },
        Product: {
            title: "Продукт",
            description: "Партнерская программа LVLX является прямым рекламодателем iGaming продуктов и предоставляет офферы на онлайн-казино и БК",
            plusOne: "In-house колл-центр",
            plusTwo: "VIP программа",
            plusThree: "KZ, RU, TR, IN",
            plusFour: "Лицензия Anjouan",
            plusFive: "Reg2dep 20-50%",
            plusSix: "Экспертная поддержка",
        },
        ForStreamers: {
            description: "Партнерка LVLX предлагает индивидуальные условия сотрудничества для стримеров, включающие различные модели оплаты: RevShare, CPA, Hybrid, FIX для достижения крутого win-win результата",
            title: "Стримерам",
            plusOne: "Уникальные бонусы",
            plusTwo: "Конвертящие промо",
            plusThree: "Быстрые выплаты",
            registrations: "регистрации",
            earnings: "доход",
            deposits: "депозитов",
            visits: "посещений",
            bacomeStreamer: "Стать стримером",
        },
        Faq: {
            title: "FAQ",
            faqItems: [
                { question: "Что такое партнерская программа LVLX?", answer: "LVLX - это удобный маркетинговый инструмент, который используют владельцы веб-ресурсов, стримеры, арбитражники, другие специалисты перфоманс-маркетинга для привлечения целевого трафика на гемблинг и беттинг офферы, такие как GETX." },
                { question: "Что такое арбитраж трафика?", answer: "Это схема заработка, при которой человек (арбитражник) покупает трафик на одном источнике и перенаправляет его на офферы рекламодателя, зарабатывая на комиссии - разнице между стоимостью привлечения трафика и доходом от конверсий." },
                { question: "Как стать партнером и зарабатывать с LVLX?", answer: "1. Зарегистрируйся на сайте партнерской программы LVLX по ссылке, дождись сообщения от менеджера, который подтвердит твой доступ в личный кабинет и поможет с запуском.\n2. Привлекай аудиторию и получай прибыль по выбранной модели сотрудничества: RevShare, CPA или Hybrid.\n3. Твое вознаграждение зависит от количества и качества трафика.\n" },
                { question: "Как и когда производятся выплаты?", answer: "По модели RevShare заработок партнера выплачиваем каждый вторник.\nПо моделям СРА и Hybrid выплачиваем 2 раза в месяц за периоды 1-15 и 16-30(31) числа месяца.\nВыплаты производятся в USDT, BTC, на карту VISA и MasterCard.\nМинимальная сумма для выплаты - $50\n" },
                { question: "Какие источники трафика мы принимаем?", answer: "Партнерка LVLX принимает все виды трафика, а именно: SEO (кроме SEO по брендовым ключам наших продуктов), PPC, ASO, UAC, Facebook, In-app, соцсети, баннерную рекламу, стримы. Также готовы обсудить любой альтернативный источник трафика.\nЗапрещено: схемы обмана игроков, мислид, фрод, мотив, так называемый куки стаффинг, игра под своей рефкой.\nКаждый запуск согласовывается с личным аффилейт менеджером.\n" },
                { question: "Что такое СРА и RevShare, какую модель лучше выбрать?", answer: "CPA - это оплата за целевое действие, в нашем случае за первый депозит приведенного тобой игрока. Ставка по CPA зависит от источника, качества и объема трафика и обсуждается в индивидуальном порядке.\nRevShare - это процент от дохода, который приносят игроки. Наша партнерка предлагаем 50% от NGR пожизненно.\nВыбор модели зависит от типа трафика, и наши менеджеры порекомендуют лучший вариант для твоего роста.\n" },
                { question: "Что такое Referal?", answer: "Прямой рекламодатель LVLX дает возможность своим партнерам зарабатывать не только на продвижении gambling продуктов и привлечении пользователей, но и на привлечении новых вебмастеров для работы с партнерской программой.\nЗарабатывай 3% от дохода реферала.\n" },
                { question: "Информация для СМИ", answer: "По любым вопросам медиа-сотрудничества, обращайся в наш PR-отдел партнерки: t.me/afflvlx\n" },
            ],
        },
        Footer: {
            text: "Монетизируй свой трафик с прямым рекламодателем iGaming продуктов.",
            email: "Электронная почта",
            register: "Зарегистрироваться",
            allRightsReserved: "2025 Все права защищены. Несанкционированное воспроизведение, публикация, передача или любая другая форма копирования строго запрещены.",
        }
    },
};

export const getTextByLanguage = () => {
    const selectedLanguage = localStorage.getItem("selectedLanguageLVLX") || "RU";
    return texts[selectedLanguage];
};